-- We need some initial patients
insert into PATIENT values ('1111', CURRENT_TIMESTAMP, TRUE, 9,  CURRENT_TIMESTAMP, FALSE);
insert into PATIENT values ('2222', CURRENT_TIMESTAMP, TRUE, 11, CURRENT_TIMESTAMP, FALSE);
insert into PATIENT values ('3333', CURRENT_TIMESTAMP, TRUE, 14, CURRENT_TIMESTAMP, FALSE);
insert into PATIENT values ('4444', CURRENT_TIMESTAMP, TRUE, 16, CURRENT_TIMESTAMP, FALSE);
insert into PATIENT values ('5555', CURRENT_TIMESTAMP, TRUE, 17, CURRENT_TIMESTAMP, FALSE);
insert into PATIENT values ('6666', CURRENT_TIMESTAMP, TRUE, 18, CURRENT_TIMESTAMP, FALSE);
insert into PATIENT values ('7777', CURRENT_TIMESTAMP, FALSE, 5, CURRENT_TIMESTAMP, FALSE);
insert into PATIENT values ('8888', CURRENT_TIMESTAMP, FALSE, 6, CURRENT_TIMESTAMP, FALSE);
insert into PATIENT values ('9999', CURRENT_TIMESTAMP, FALSE, 7, CURRENT_TIMESTAMP, FALSE);
