-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE PATIENT (PIN CHAR(4) NOT NULL, NEXT_READING TIMESTAMP, IS_ANDROID BOOLEAN DEFAULT TRUE NOT NULL, OS_VERSION INTEGER, DATE_STARTED TIMESTAMP, IS_COMPLETED BOOLEAN DEFAULT FALSE NOT NULL);
CREATE TABLE SURVEY_RESULT (PATIENT_ID CHAR(4) NOT NULL, DATE_TIME TIMESTAMP NOT NULL);
CREATE TABLE SURVEY_RESULT_ANSWER (ANSWER_COMPONENT_ID VARCHAR(32) NOT NULL, QUESTION_ID VARCHAR(32) NOT NULL, PATIENT_ID CHAR(4) NOT NULL, DATE_TIME TIMESTAMP NOT NULL, VALUE VARCHAR(2048) NOT NULL);
CREATE TABLE EVENT (EVENT_ID INTEGER NOT NULL, PATIENT_ID CHAR(4), EVENTTYPE VARCHAR(16) NOT NULL, EVENTVALUE VARCHAR(1024) NOT NULL, EVENTTIME TIMESTAMP NOT NULL);

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- primary/unique
ALTER TABLE PATIENT ADD CONSTRAINT PATIENT_PK PRIMARY KEY (PIN);
ALTER TABLE SURVEY_RESULT ADD CONSTRAINT SURVEY_RESULT_PK PRIMARY KEY (PATIENT_ID, DATE_TIME);
ALTER TABLE SURVEY_RESULT_ANSWER ADD CONSTRAINT SURVEY_RESULT_ANSWER PRIMARY KEY (ANSWER_COMPONENT_ID, QUESTION_ID, PATIENT_ID, DATE_TIME);
ALTER TABLE EVENT add constraint EVENT_PK primary key (EVENT_ID);

-- foreign
ALTER TABLE SURVEY_RESULT ADD CONSTRAINT PATIENT_FK FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT (PIN) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE SURVEY_RESULT_ANSWER ADD CONSTRAINT SURVEY_RESULT_FK FOREIGN KEY (PATIENT_ID,DATE_TIME) REFERENCES SURVEY_RESULT (PATIENT_ID,DATE_TIME) ON DELETE NO ACTION ON UPDATE NO ACTION;

